#pragma once

/*
 * Deployment is a bounded, little-endian byte format.  These constants name
 * byte offsets and semantic values; they are not permission to cast a table
 * record to a C object.  Readers must decode each field explicitly.
 */
#ifndef __ASSEMBLER__
#include <stdint.h>
#endif

#define MYOS_DEPLOY_MAGIC UINT64_C(0x594f4c504544534d) /* "MSDEPLOY" */
#define MYOS_DEPLOY_MAJOR 1
#define MYOS_DEPLOY_MINOR 0
#define MYOS_DEPLOY_HEADER_SIZE 208U
#define MYOS_DEPLOY_TABLE_COUNT 9U
#define MYOS_DEPLOY_TABLE_DESC_SIZE 16U
#define MYOS_DEPLOY_MAX_SIZE (UINT64_C(1) << 20)
#define MYOS_DEPLOY_TABLE_ALIGNMENT 8U
#define MYOS_DEPLOY_PAGE_SIZE 4096U
#define MYOS_DEPLOY_STRING_MAX (256U * 1024U)
#define MYOS_DEPLOY_NO_INDEX UINT32_MAX
#define MYOS_DEPLOY_HOME_CPU_ANY 0xffffffffU
#define MYOS_DEPLOY_CPU_MAX 256U
#define MYOS_DEPLOY_URGENCY_MAX 31U

#define MYOS_DEPLOY_ARCH_GENERIC 0U
#define MYOS_DEPLOY_ABI_ID 1U

#define MYOS_DEPLOY_HEADER_MAGIC 0U
#define MYOS_DEPLOY_HEADER_MAJOR 8U
#define MYOS_DEPLOY_HEADER_MINOR 10U
#define MYOS_DEPLOY_HEADER_SIZE_FIELD 12U
#define MYOS_DEPLOY_HEADER_TOTAL_SIZE 16U
#define MYOS_DEPLOY_HEADER_ARCHITECTURE 24U
#define MYOS_DEPLOY_HEADER_ABI 28U
#define MYOS_DEPLOY_HEADER_FEATURES 32U
#define MYOS_DEPLOY_HEADER_FLAGS 40U
#define MYOS_DEPLOY_HEADER_CHECKSUM 48U
#define MYOS_DEPLOY_HEADER_TABLE_COUNT 56U
#define MYOS_DEPLOY_HEADER_RESERVED 60U
#define MYOS_DEPLOY_HEADER_TABLES 64U

#define MYOS_DEPLOY_TABLE_TASK 0U
#define MYOS_DEPLOY_TABLE_IMAGE 1U
#define MYOS_DEPLOY_TABLE_MAPPING 2U
#define MYOS_DEPLOY_TABLE_OBJECT 3U
#define MYOS_DEPLOY_TABLE_EXECUTION 4U
#define MYOS_DEPLOY_TABLE_IMPORT 5U
#define MYOS_DEPLOY_TABLE_DEPENDENCY 6U
#define MYOS_DEPLOY_TABLE_EXPORT 7U
#define MYOS_DEPLOY_TABLE_STRING 8U

#define MYOS_DEPLOY_TASK_STRIDE 160U
#define MYOS_DEPLOY_IMAGE_STRIDE 32U
#define MYOS_DEPLOY_MAPPING_STRIDE 80U
#define MYOS_DEPLOY_OBJECT_STRIDE 96U
#define MYOS_DEPLOY_EXECUTION_STRIDE 112U
#define MYOS_DEPLOY_IMPORT_STRIDE 96U
#define MYOS_DEPLOY_DEPENDENCY_STRIDE 32U
#define MYOS_DEPLOY_EXPORT_STRIDE 96U

#define MYOS_DEPLOY_TASK_MAX 64U
#define MYOS_DEPLOY_IMAGE_MAX 128U
#define MYOS_DEPLOY_MAPPING_MAX 1024U
#define MYOS_DEPLOY_OBJECT_MAX 512U
#define MYOS_DEPLOY_EXECUTION_MAX 256U
#define MYOS_DEPLOY_IMPORT_MAX 1024U
#define MYOS_DEPLOY_DEPENDENCY_MAX 1024U
#define MYOS_DEPLOY_EXPORT_MAX 512U

#define MYOS_DEPLOY_TASK_IMAGE_MAX 8U
#define MYOS_DEPLOY_TASK_MAPPING_MAX 128U
#define MYOS_DEPLOY_TASK_OBJECT_MAX 64U
#define MYOS_DEPLOY_TASK_EXECUTION_MAX 16U
#define MYOS_DEPLOY_TASK_IMPORT_MAX 128U
#define MYOS_DEPLOY_TASK_DEPENDENCY_MAX 128U
#define MYOS_DEPLOY_TASK_EXPORT_MAX 64U

/* Fixed envelope table descriptor fields. */
#define MYOS_DEPLOY_TABLE_OFFSET 0U
#define MYOS_DEPLOY_TABLE_COUNT_FIELD 8U
#define MYOS_DEPLOY_TABLE_STRIDE 12U

/* Task record fields. */
#define MYOS_DEPLOY_TASK_NAME 0U
#define MYOS_DEPLOY_TASK_POOL 8U
#define MYOS_DEPLOY_TASK_VSPACE 16U
#define MYOS_DEPLOY_TASK_CSPACE 24U
#define MYOS_DEPLOY_TASK_IMAGE_FIRST 32U
#define MYOS_DEPLOY_TASK_IMAGE_COUNT 36U
#define MYOS_DEPLOY_TASK_MAPPING_FIRST 40U
#define MYOS_DEPLOY_TASK_MAPPING_COUNT 44U
#define MYOS_DEPLOY_TASK_OBJECT_FIRST 48U
#define MYOS_DEPLOY_TASK_OBJECT_COUNT 52U
#define MYOS_DEPLOY_TASK_EXECUTION_FIRST 56U
#define MYOS_DEPLOY_TASK_EXECUTION_COUNT 60U
#define MYOS_DEPLOY_TASK_IMPORT_FIRST 64U
#define MYOS_DEPLOY_TASK_IMPORT_COUNT 68U
#define MYOS_DEPLOY_TASK_DEPENDENCY_FIRST 72U
#define MYOS_DEPLOY_TASK_DEPENDENCY_COUNT 76U
#define MYOS_DEPLOY_TASK_EXPORT_FIRST 80U
#define MYOS_DEPLOY_TASK_EXPORT_COUNT 84U
#define MYOS_DEPLOY_TASK_POOL_MEMORY 88U
#define MYOS_DEPLOY_TASK_POOL_CAPS 96U
#define MYOS_DEPLOY_TASK_KIND_MASK 104U
#define MYOS_DEPLOY_TASK_CRITICAL_BYTES 112U
#define MYOS_DEPLOY_TASK_CSPACE_SLOTS 120U
#define MYOS_DEPLOY_TASK_CSPACE_PAGES 124U
#define MYOS_DEPLOY_TASK_BOOTSTRAP_MAPPING 128U
#define MYOS_DEPLOY_TASK_FLAGS 132U
#define MYOS_DEPLOY_TASK_READINESS 136U
#define MYOS_DEPLOY_TASK_TERMINAL 138U
#define MYOS_DEPLOY_TASK_RESTART 140U
#define MYOS_DEPLOY_TASK_RESERVED 142U
#define MYOS_DEPLOY_TASK_READINESS_VALUE 144U
#define MYOS_DEPLOY_TASK_RESERVED_TAIL 152U

/* Image record fields. */
#define MYOS_DEPLOY_IMAGE_SOURCE 0U
#define MYOS_DEPLOY_IMAGE_SOURCE_KIND 8U
#define MYOS_DEPLOY_IMAGE_FLAGS 10U
#define MYOS_DEPLOY_IMAGE_RESERVED 12U

/* Mapping record fields. */
#define MYOS_DEPLOY_MAPPING_PRODUCED 0U
#define MYOS_DEPLOY_MAPPING_PAGER 8U
#define MYOS_DEPLOY_MAPPING_IMAGE 16U
#define MYOS_DEPLOY_MAPPING_SEGMENT 20U
#define MYOS_DEPLOY_MAPPING_SOURCE 24U
#define MYOS_DEPLOY_MAPPING_RESIDENCY 26U
#define MYOS_DEPLOY_MAPPING_CRITICAL 28U
#define MYOS_DEPLOY_MAPPING_FLAGS 30U
#define MYOS_DEPLOY_MAPPING_ACCESS 32U
#define MYOS_DEPLOY_MAPPING_PAGER_POLICY 36U
#define MYOS_DEPLOY_MAPPING_ADDRESS 40U
#define MYOS_DEPLOY_MAPPING_SIZE 48U
#define MYOS_DEPLOY_MAPPING_RESERVED 56U

/* Object record fields. */
#define MYOS_DEPLOY_OBJECT_OUTPUT 0U
#define MYOS_DEPLOY_OBJECT_OUTPUT_A 0U
#define MYOS_DEPLOY_OBJECT_OUTPUT_B 8U
#define MYOS_DEPLOY_OBJECT_KIND 16U
#define MYOS_DEPLOY_OBJECT_FLAGS 18U
#define MYOS_DEPLOY_OBJECT_RESERVED 20U
#define MYOS_DEPLOY_OBJECT_REF0 24U
#define MYOS_DEPLOY_OBJECT_REF1 28U
#define MYOS_DEPLOY_OBJECT_REF2 32U
#define MYOS_DEPLOY_OBJECT_REF3 36U
#define MYOS_DEPLOY_OBJECT_ARG0 40U
#define MYOS_DEPLOY_OBJECT_ARG1 48U
#define MYOS_DEPLOY_OBJECT_ARG2 56U
#define MYOS_DEPLOY_OBJECT_ARG3 64U
#define MYOS_DEPLOY_OBJECT_ARG4 72U
#define MYOS_DEPLOY_OBJECT_ARG5 80U
#define MYOS_DEPLOY_OBJECT_RESERVED_TAIL 88U

/* Execution record fields. */
#define MYOS_DEPLOY_EXECUTION_KEY 0U
#define MYOS_DEPLOY_EXECUTION_SC 8U
#define MYOS_DEPLOY_EXECUTION_DOMAIN 16U
#define MYOS_DEPLOY_EXECUTION_IMAGE 24U
#define MYOS_DEPLOY_EXECUTION_STACK 28U
#define MYOS_DEPLOY_EXECUTION_BOOTSTRAP 32U
#define MYOS_DEPLOY_EXECUTION_IPC 36U
#define MYOS_DEPLOY_EXECUTION_CONTROL 40U
#define MYOS_DEPLOY_EXECUTION_EVENT 44U
#define MYOS_DEPLOY_EXECUTION_MODEL 48U
#define MYOS_DEPLOY_EXECUTION_FLAGS 50U
#define MYOS_DEPLOY_EXECUTION_FAULT 52U
#define MYOS_DEPLOY_EXECUTION_TERMINAL 54U
#define MYOS_DEPLOY_EXECUTION_ENTRY 56U
#define MYOS_DEPLOY_EXECUTION_STACK_TOP 64U
#define MYOS_DEPLOY_EXECUTION_SC_BUDGET 72U
#define MYOS_DEPLOY_EXECUTION_SC_PERIOD 80U
#define MYOS_DEPLOY_EXECUTION_URGENCY 88U
#define MYOS_DEPLOY_EXECUTION_HOME_CPU 92U
#define MYOS_DEPLOY_EXECUTION_RESERVED 96U

/* Import record fields. */
#define MYOS_DEPLOY_IMPORT_SOURCE 0U
#define MYOS_DEPLOY_IMPORT_DESTINATION 8U
#define MYOS_DEPLOY_IMPORT_MODE 16U
#define MYOS_DEPLOY_IMPORT_SELECTOR 18U
#define MYOS_DEPLOY_IMPORT_FLAGS 20U
#define MYOS_DEPLOY_IMPORT_ATTENUATION 24U
#define MYOS_DEPLOY_IMPORT_RESERVED 88U

/* Dependency record fields. */
#define MYOS_DEPLOY_DEPENDENCY_TARGET 0U
#define MYOS_DEPLOY_DEPENDENCY_KIND 4U
#define MYOS_DEPLOY_DEPENDENCY_FLAGS 6U
#define MYOS_DEPLOY_DEPENDENCY_RELATION 8U
#define MYOS_DEPLOY_DEPENDENCY_RESERVED 16U

/* Export record fields. */
#define MYOS_DEPLOY_EXPORT_SOURCE 0U
#define MYOS_DEPLOY_EXPORT_KEY 8U
#define MYOS_DEPLOY_EXPORT_CLASS 16U
#define MYOS_DEPLOY_EXPORT_FLAGS 18U
#define MYOS_DEPLOY_EXPORT_RESERVED 20U
#define MYOS_DEPLOY_EXPORT_CEILING 24U
#define MYOS_DEPLOY_EXPORT_RESERVED_TAIL 88U

/* Source-relative attenuation descriptor fields. */
#include <uapi/capability.h>

/* Deployment wire offsets are aliases of the canonical capability ABI. */
#define MYOS_DEPLOY_ATTENUATION_VERSION \
    MYOS_CAP_ATTENUATION_VERSION_OFFSET
#define MYOS_DEPLOY_ATTENUATION_KIND MYOS_CAP_ATTENUATION_KIND_OFFSET
#define MYOS_DEPLOY_ATTENUATION_SIZE MYOS_CAP_ATTENUATION_SIZE_OFFSET
#define MYOS_DEPLOY_ATTENUATION_RIGHTS MYOS_CAP_ATTENUATION_RIGHTS_OFFSET
#define MYOS_DEPLOY_ATTENUATION_WORD0 MYOS_CAP_ATTENUATION_WORD0_OFFSET
#define MYOS_DEPLOY_ATTENUATION_WORD1 MYOS_CAP_ATTENUATION_WORD1_OFFSET
#define MYOS_DEPLOY_ATTENUATION_WORD2 MYOS_CAP_ATTENUATION_WORD2_OFFSET
#define MYOS_DEPLOY_ATTENUATION_WORD3 MYOS_CAP_ATTENUATION_WORD3_OFFSET
#define MYOS_DEPLOY_ATTENUATION_WORD4 MYOS_CAP_ATTENUATION_WORD4_OFFSET
#define MYOS_DEPLOY_ATTENUATION_WORD5 MYOS_CAP_ATTENUATION_WORD5_OFFSET
#define MYOS_DEPLOY_ATTENUATION_STRIDE MYOS_CAP_ATTENUATION_SIZE
#define MYOS_DEPLOY_ATTENUATION_VERSION_CURRENT \
    MYOS_CAP_ATTENUATION_VERSION_CURRENT

#ifndef __ASSEMBLER__

typedef enum myos_deploy_table {
    MYOS_DEPLOY_TABLE_KIND_TASK = MYOS_DEPLOY_TABLE_TASK,
    MYOS_DEPLOY_TABLE_KIND_IMAGE = MYOS_DEPLOY_TABLE_IMAGE,
    MYOS_DEPLOY_TABLE_KIND_MAPPING = MYOS_DEPLOY_TABLE_MAPPING,
    MYOS_DEPLOY_TABLE_KIND_OBJECT = MYOS_DEPLOY_TABLE_OBJECT,
    MYOS_DEPLOY_TABLE_KIND_EXECUTION = MYOS_DEPLOY_TABLE_EXECUTION,
    MYOS_DEPLOY_TABLE_KIND_IMPORT = MYOS_DEPLOY_TABLE_IMPORT,
    MYOS_DEPLOY_TABLE_KIND_DEPENDENCY = MYOS_DEPLOY_TABLE_DEPENDENCY,
    MYOS_DEPLOY_TABLE_KIND_EXPORT = MYOS_DEPLOY_TABLE_EXPORT,
    MYOS_DEPLOY_TABLE_KIND_STRING = MYOS_DEPLOY_TABLE_STRING,
} myos_deploy_table_t;

typedef enum myos_deploy_architecture {
    MYOS_DEPLOY_ARCHITECTURE_GENERIC = MYOS_DEPLOY_ARCH_GENERIC,
} myos_deploy_architecture_t;

typedef enum myos_deploy_image_source_kind {
    MYOS_DEPLOY_IMAGE_SOURCE_BOOT_BUNDLE = 0,
} myos_deploy_image_source_kind_t;

typedef enum myos_deploy_mapping_source {
    MYOS_DEPLOY_MAPPING_SOURCE_IMAGE_SEGMENT = 0,
    MYOS_DEPLOY_MAPPING_SOURCE_ZERO = 1,
    MYOS_DEPLOY_MAPPING_SOURCE_PAGER = 2,
} myos_deploy_mapping_source_t;

typedef enum myos_deploy_mapping_residency {
    MYOS_DEPLOY_MAPPING_RESIDENT = 0,
    MYOS_DEPLOY_MAPPING_PAGEABLE = 1,
} myos_deploy_mapping_residency_t;

typedef enum myos_deploy_mapping_critical {
    MYOS_DEPLOY_CRITICAL_NONE = 0,
    MYOS_DEPLOY_CRITICAL_CODE = 1,
    MYOS_DEPLOY_CRITICAL_STACK = 2,
    MYOS_DEPLOY_CRITICAL_BOOTSTRAP = 3,
    MYOS_DEPLOY_CRITICAL_LOADER = 4,
    MYOS_DEPLOY_CRITICAL_PAGER_RECOVERY = 5,
    MYOS_DEPLOY_CRITICAL_DRIVER_RECOVERY = 6,
    MYOS_DEPLOY_CRITICAL_VPROC_CONTROL = 7,
    MYOS_DEPLOY_CRITICAL_VPROC_EVENT = 8,
    MYOS_DEPLOY_CRITICAL_IPC_HEADER = 9,
} myos_deploy_mapping_critical_t;

#define MYOS_DEPLOY_OBJECT_FLAG_NONE 0U
#define MYOS_DEPLOY_OBJECT_EPHEMERAL_TASK (1U << 0)
#define MYOS_DEPLOY_OBJECT_POST_MAPPING (1U << 1)
#define MYOS_DEPLOY_OBJECT_FLAGS_VALID \
    (MYOS_DEPLOY_OBJECT_EPHEMERAL_TASK | MYOS_DEPLOY_OBJECT_POST_MAPPING)

typedef enum myos_deploy_import_mode {
    MYOS_DEPLOY_IMPORT_TYPED_DELEGATE = 0,
    MYOS_DEPLOY_IMPORT_DUPLICATE = 1,
    MYOS_DEPLOY_IMPORT_CHANNEL_MINT = 2,
    MYOS_DEPLOY_IMPORT_MOVE = 3,
} myos_deploy_import_mode_t;

typedef enum myos_deploy_selector_policy {
    MYOS_DEPLOY_SELECTOR_ALLOCATED_KEYED = 0,
} myos_deploy_selector_policy_t;

typedef enum myos_deploy_dependency_kind {
    MYOS_DEPLOY_DEPENDENCY_REQUIRED = 0,
    MYOS_DEPLOY_DEPENDENCY_OPTIONAL = 1,
} myos_deploy_dependency_kind_t;

#define MYOS_DEPLOY_DEPENDENCY_STARTUP (1U << 0)
#define MYOS_DEPLOY_DEPENDENCY_READINESS (1U << 1)
#define MYOS_DEPLOY_DEPENDENCY_FLAGS_VALID \
    (MYOS_DEPLOY_DEPENDENCY_STARTUP | MYOS_DEPLOY_DEPENDENCY_READINESS)

typedef enum myos_deploy_export_class {
    MYOS_DEPLOY_EXPORT_PREPARED_KEY = 0,
    MYOS_DEPLOY_EXPORT_RUNTIME_READY = 1,
} myos_deploy_export_class_t;

typedef enum myos_deploy_execution_model {
    MYOS_DEPLOY_EXECUTION_THREAD = 0,
    MYOS_DEPLOY_EXECUTION_VPROC = 1,
} myos_deploy_execution_model_t;

/* Fault policy is target-specific even though its wire field is shared. */
typedef enum myos_deploy_execution_fault_policy {
    MYOS_DEPLOY_EXECUTION_FAULT_TERMINATE = 0,
    MYOS_DEPLOY_EXECUTION_FAULT_ENDPOINT = 1,
    MYOS_DEPLOY_EXECUTION_FAULT_RUNTIME = 1,
} myos_deploy_execution_fault_policy_t;

typedef enum myos_deploy_execution_terminal_policy {
    MYOS_DEPLOY_EXECUTION_TERMINAL_LEADER_EXIT = 0,
    MYOS_DEPLOY_EXECUTION_TERMINAL_ALL_EXIT = 1,
    MYOS_DEPLOY_EXECUTION_TERMINAL_ANY_FAILURE = 2,
    MYOS_DEPLOY_EXECUTION_TERMINAL_SUPERVISOR_MANAGED = 3,
} myos_deploy_execution_terminal_policy_t;

typedef enum myos_deploy_readiness_policy {
    MYOS_DEPLOY_READINESS_NONE = 0,
    MYOS_DEPLOY_READINESS_START = 1,
    MYOS_DEPLOY_READINESS_EXPLICIT = 2,
} myos_deploy_readiness_policy_t;

typedef enum myos_deploy_terminal_policy {
    MYOS_DEPLOY_TERMINAL_RETAIN = 0,
    MYOS_DEPLOY_TERMINAL_RESTART = 1,
    MYOS_DEPLOY_TERMINAL_CLOSE = 2,
} myos_deploy_terminal_policy_t;

typedef enum myos_deploy_restart_policy {
    MYOS_DEPLOY_RESTART_NEVER = 0,
    MYOS_DEPLOY_RESTART_ON_FAULT = 1,
    MYOS_DEPLOY_RESTART_ALWAYS = 2,
} myos_deploy_restart_policy_t;

#endif
