#pragma once

#include <uapi/object.h>

// Typed constructor authority mask. These values are ABI identifiers, not
// generic object_create tags: each admitted kind still has a distinct syscall.
#define RESOURCE_THREAD \
    (UINT64_C(1) << OBJECT_KIND_THREAD)
#define RESOURCE_SCHED_CONTEXT \
    (UINT64_C(1) << OBJECT_KIND_SCHED_CONTEXT)
#define RESOURCE_SCHED_DOMAIN \
    (UINT64_C(1) << OBJECT_KIND_SCHED_DOMAIN)
#define RESOURCE_CSPACE \
    (UINT64_C(1) << OBJECT_KIND_CSPACE)
#define RESOURCE_MEMORY \
    (UINT64_C(1) << OBJECT_KIND_MEMORY)
#define RESOURCE_VSPACE \
    (UINT64_C(1) << OBJECT_KIND_VSPACE)
#define RESOURCE_POOL \
    (UINT64_C(1) << OBJECT_KIND_RESOURCE_POOL)
#define RESOURCE_NOTIFICATION \
    (UINT64_C(1) << OBJECT_KIND_NOTIFICATION)
#define RESOURCE_ENDPOINT \
    (UINT64_C(1) << OBJECT_KIND_ENDPOINT)
#define RESOURCE_CHANNEL \
    (UINT64_C(1) << OBJECT_KIND_CHANNEL)
#define RESOURCE_PAGER \
    (UINT64_C(1) << OBJECT_KIND_PAGER)
#define RESOURCE_IRQ \
    (UINT64_C(1) << OBJECT_KIND_IRQ)
#define RESOURCE_IO_SPACE \
    (UINT64_C(1) << OBJECT_KIND_IO_SPACE)

#define RESOURCE_E1_KINDS ( \
    RESOURCE_THREAD | RESOURCE_SCHED_CONTEXT | \
    RESOURCE_CSPACE | RESOURCE_MEMORY | \
    RESOURCE_VSPACE | RESOURCE_POOL)

#define RESOURCE_E2_KINDS ( \
    RESOURCE_E1_KINDS | RESOURCE_NOTIFICATION)

#define RESOURCE_E3_KINDS ( \
    RESOURCE_E2_KINDS)

#define RESOURCE_E4_KINDS ( \
    RESOURCE_E3_KINDS | RESOURCE_ENDPOINT)

#define RESOURCE_E6_KINDS ( \
    RESOURCE_E4_KINDS | RESOURCE_CHANNEL)

#define RESOURCE_E7_KINDS ( \
    RESOURCE_E6_KINDS | RESOURCE_PAGER | RESOURCE_IRQ)
