#pragma once

#define SSTATUS_SPP_MASK 0x100
#define CPU_ENTRY_T0_OFF 0
#define CPU_ENTRY_T1_OFF 8
#define CPU_ENTRY_T2_OFF 16
#define CPU_ENTRY_SP_OFF 24
#define CPU_ENTRY_SIZE 32
#define CPU_ENTRY_OWNER_OFF 32
#define CPU_ENTRY_STACK_OFF 40
#define CPU_ENTRY_DEPTH_OFF 48
#define CPU_ENTRY_EMERGENCY_STACK_OFF 56
#define CPU_ENTRY_PANIC_OFF 64
#define CPU_ENTRY_EMERGENCY_DEPTH_OFF 72
#define CPU_ENTRY_STOP_OFF 80
#define CPU_ENTRY_TICK_OFF 88
#define CPU_ENTRY_BLOCK_SIZE 96
#define CPU_START_READY_OFF 0
#define CPU_START_HART_OFF 8
#define CPU_START_ROOT_OFF 16
#define CPU_START_STACK_OFF 24
#define CPU_START_ARG_OFF 32
#define CPU_START_ENTRY_OFF 40
#define CPU_START_SIZE 48
#define CPU_START_READY 0x43505552

#define CPU_CTX_RA_OFF 0
#define CPU_CTX_SP_OFF 8
#define CPU_CTX_S_OFF 16
#define CPU_CTX_SIZE 112
